package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Busdetails generated by hbm2java
 */
@Entity
@Table(name="busdetails"
    ,catalog="travelandtourism"
)
public class Busdetails  implements java.io.Serializable {


     private Integer busid;
     private String busname;
     private String start;
     private String end;
     private double fare;
     private String status;
     private int transdetid;

    public Busdetails() {
    }

    public Busdetails(String busname, String start, String end, double fare, String status, int transdetid) {
       this.busname = busname;
       this.start = start;
       this.end = end;
       this.fare = fare;
       this.status = status;
       this.transdetid = transdetid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="busid", unique=true, nullable=false)
    public Integer getBusid() {
        return this.busid;
    }
    
    public void setBusid(Integer busid) {
        this.busid = busid;
    }

    
    @Column(name="busname", nullable=false, length=45)
    public String getBusname() {
        return this.busname;
    }
    
    public void setBusname(String busname) {
        this.busname = busname;
    }

    
    @Column(name="start", nullable=false, length=45)
    public String getStart() {
        return this.start;
    }
    
    public void setStart(String start) {
        this.start = start;
    }

    
    @Column(name="end", nullable=false, length=45)
    public String getEnd() {
        return this.end;
    }
    
    public void setEnd(String end) {
        this.end = end;
    }

    
    @Column(name="fare", nullable=false, precision=22, scale=0)
    public double getFare() {
        return this.fare;
    }
    
    public void setFare(double fare) {
        this.fare = fare;
    }

    
    @Column(name="status", nullable=false, length=450)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="transdetid", nullable=false)
    public int getTransdetid() {
        return this.transdetid;
    }
    
    public void setTransdetid(int transdetid) {
        this.transdetid = transdetid;
    }




}


