package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customerbooking generated by hbm2java
 */
@Entity
@Table(name="customerbooking"
    ,catalog="travelandtourism"
)
public class Customerbooking  implements java.io.Serializable {


     private Integer bookingid;
     private int custid;
     private int tpackid;
     private String tourstart;
     private String tourend;
     private int totalperson;
     private Date bookingdate;

    public Customerbooking() {
    }

    public Customerbooking(int custid, int tpackid, String tourstart, String tourend, int totalperson, Date bookingdate) {
       this.custid = custid;
       this.tpackid = tpackid;
       this.tourstart = tourstart;
       this.tourend = tourend;
       this.totalperson = totalperson;
       this.bookingdate = bookingdate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="bookingid", unique=true, nullable=false)
    public Integer getBookingid() {
        return this.bookingid;
    }
    
    public void setBookingid(Integer bookingid) {
        this.bookingid = bookingid;
    }

    
    @Column(name="custid", nullable=false)
    public int getCustid() {
        return this.custid;
    }
    
    public void setCustid(int custid) {
        this.custid = custid;
    }

    
    @Column(name="tpackid", nullable=false)
    public int getTpackid() {
        return this.tpackid;
    }
    
    public void setTpackid(int tpackid) {
        this.tpackid = tpackid;
    }

    
    @Column(name="tourstart", nullable=false, length=45)
    public String getTourstart() {
        return this.tourstart;
    }
    
    public void setTourstart(String tourstart) {
        this.tourstart = tourstart;
    }

    
    @Column(name="tourend", nullable=false, length=45)
    public String getTourend() {
        return this.tourend;
    }
    
    public void setTourend(String tourend) {
        this.tourend = tourend;
    }

    
    @Column(name="totalperson", nullable=false)
    public int getTotalperson() {
        return this.totalperson;
    }
    
    public void setTotalperson(int totalperson) {
        this.totalperson = totalperson;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bookingdate", nullable=false, length=19)
    public Date getBookingdate() {
        return this.bookingdate;
    }
    
    public void setBookingdate(Date bookingdate) {
        this.bookingdate = bookingdate;
    }




}


