package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Custbookingguide generated by hbm2java
 */
@Entity
@Table(name="custbookingguide"
    ,catalog="travelandtourism"
)
public class Custbookingguide  implements java.io.Serializable {


     private Integer custguideid;
     private int bookingid;
     private int gid;
     private double rate;
     private Date bookingdate;

    public Custbookingguide() {
    }

    public Custbookingguide(int bookingid, int gid, double rate, Date bookingdate) {
       this.bookingid = bookingid;
       this.gid = gid;
       this.rate = rate;
       this.bookingdate = bookingdate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="custguideid", unique=true, nullable=false)
    public Integer getCustguideid() {
        return this.custguideid;
    }
    
    public void setCustguideid(Integer custguideid) {
        this.custguideid = custguideid;
    }

    
    @Column(name="bookingid", nullable=false)
    public int getBookingid() {
        return this.bookingid;
    }
    
    public void setBookingid(int bookingid) {
        this.bookingid = bookingid;
    }

    
    @Column(name="gid", nullable=false)
    public int getGid() {
        return this.gid;
    }
    
    public void setGid(int gid) {
        this.gid = gid;
    }

    
    @Column(name="rate", nullable=false, precision=22, scale=0)
    public double getRate() {
        return this.rate;
    }
    
    public void setRate(double rate) {
        this.rate = rate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bookingdate", nullable=false, length=10)
    public Date getBookingdate() {
        return this.bookingdate;
    }
    
    public void setBookingdate(Date bookingdate) {
        this.bookingdate = bookingdate;
    }




}


