package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name="feedback"
    ,catalog="travelandtourism"
)
public class Feedback  implements java.io.Serializable {


     private Integer fid;
     private int custid;
     private String feedbackfor;
     private String comment;

    public Feedback() {
    }

    public Feedback(int custid, String feedbackfor, String comment) {
       this.custid = custid;
       this.feedbackfor = feedbackfor;
       this.comment = comment;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fid", unique=true, nullable=false)
    public Integer getFid() {
        return this.fid;
    }
    
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    
    @Column(name="custid", nullable=false)
    public int getCustid() {
        return this.custid;
    }
    
    public void setCustid(int custid) {
        this.custid = custid;
    }

    
    @Column(name="feedbackfor", nullable=false, length=45)
    public String getFeedbackfor() {
        return this.feedbackfor;
    }
    
    public void setFeedbackfor(String feedbackfor) {
        this.feedbackfor = feedbackfor;
    }

    
    @Column(name="comment", nullable=false, length=450)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


