package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hotelagent generated by hbm2java
 */
@Entity
@Table(name="hotelagent"
    ,catalog="travelandtourism"
)
public class Hotelagent  implements java.io.Serializable {


     private Integer hagentid;
     private String hagentname;
     private String hagentmobile;
     private String hagentaddress;
     private String emailid;

    public Hotelagent() {
    }

    public Hotelagent(String hagentname, String hagentmobile, String hagentaddress, String emailid) {
       this.hagentname = hagentname;
       this.hagentmobile = hagentmobile;
       this.hagentaddress = hagentaddress;
       this.emailid = emailid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="hagentid", unique=true, nullable=false)
    public Integer getHagentid() {
        return this.hagentid;
    }
    
    public void setHagentid(Integer hagentid) {
        this.hagentid = hagentid;
    }

    
    @Column(name="hagentname", nullable=false, length=45)
    public String getHagentname() {
        return this.hagentname;
    }
    
    public void setHagentname(String hagentname) {
        this.hagentname = hagentname;
    }

    
    @Column(name="hagentmobile", nullable=false, length=45)
    public String getHagentmobile() {
        return this.hagentmobile;
    }
    
    public void setHagentmobile(String hagentmobile) {
        this.hagentmobile = hagentmobile;
    }

    
    @Column(name="hagentaddress", nullable=false, length=450)
    public String getHagentaddress() {
        return this.hagentaddress;
    }
    
    public void setHagentaddress(String hagentaddress) {
        this.hagentaddress = hagentaddress;
    }

    
    @Column(name="emailid", nullable=false, length=45)
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }




}


