package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hoteldetails generated by hbm2java
 */
@Entity
@Table(name="hoteldetails"
    ,catalog="travelandtourism"
)
public class Hoteldetails  implements java.io.Serializable {


     private Integer hdetid;
     private int hagentid;
     private String roomtype;
     private double rent;
     private String facilities;
     private String type;
     private String imgurl;

    public Hoteldetails() {
    }

    public Hoteldetails(int hagentid, String roomtype, double rent, String facilities, String type, String imgurl) {
       this.hagentid = hagentid;
       this.roomtype = roomtype;
       this.rent = rent;
       this.facilities = facilities;
       this.type = type;
       this.imgurl = imgurl;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="hdetid", unique=true, nullable=false)
    public Integer getHdetid() {
        return this.hdetid;
    }
    
    public void setHdetid(Integer hdetid) {
        this.hdetid = hdetid;
    }

    
    @Column(name="hagentid", nullable=false)
    public int getHagentid() {
        return this.hagentid;
    }
    
    public void setHagentid(int hagentid) {
        this.hagentid = hagentid;
    }

    
    @Column(name="roomtype", nullable=false, length=45)
    public String getRoomtype() {
        return this.roomtype;
    }
    
    public void setRoomtype(String roomtype) {
        this.roomtype = roomtype;
    }

    
    @Column(name="rent", nullable=false, precision=22, scale=0)
    public double getRent() {
        return this.rent;
    }
    
    public void setRent(double rent) {
        this.rent = rent;
    }

    
    @Column(name="facilities", nullable=false, length=1000)
    public String getFacilities() {
        return this.facilities;
    }
    
    public void setFacilities(String facilities) {
        this.facilities = facilities;
    }

    
    @Column(name="type", nullable=false, length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="imgurl", nullable=false, length=450)
    public String getImgurl() {
        return this.imgurl;
    }
    
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }




}


