package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hotelimage generated by hbm2java
 */
@Entity
@Table(name="hotelimage"
    ,catalog="travelandtourism"
)
public class Hotelimage  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String type;
     private byte[] picByte;

    public Hotelimage() {
    }

    public Hotelimage(String name, String type, byte[] picByte) {
       this.name = name;
       this.type = type;
       this.picByte = picByte;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="type", nullable=false, length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="picByte", nullable=false)
    public byte[] getPicByte() {
        return this.picByte;
    }
    
    public void setPicByte(byte[] picByte) {
        this.picByte = picByte;
    }




}


