package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Transtype generated by hbm2java
 */
@Entity
@Table(name="transtype"
    ,catalog="travelandtourism"
)
public class Transtype  implements java.io.Serializable {


     private int id;
     private String bus;
     private String car;
     private String status;
     private String hotel;
     private String resort;

    public Transtype() {
    }

    public Transtype(int id, String bus, String car, String status, String hotel, String resort) {
       this.id = id;
       this.bus = bus;
       this.car = car;
       this.status = status;
       this.hotel = hotel;
       this.resort = resort;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="bus", nullable=false, length=45)
    public String getBus() {
        return this.bus;
    }
    
    public void setBus(String bus) {
        this.bus = bus;
    }

    
    @Column(name="car", nullable=false, length=45)
    public String getCar() {
        return this.car;
    }
    
    public void setCar(String car) {
        this.car = car;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="hotel", nullable=false, length=45)
    public String getHotel() {
        return this.hotel;
    }
    
    public void setHotel(String hotel) {
        this.hotel = hotel;
    }

    
    @Column(name="resort", nullable=false, length=45)
    public String getResort() {
        return this.resort;
    }
    
    public void setResort(String resort) {
        this.resort = resort;
    }




}


