package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Transportagent generated by hbm2java
 */
@Entity
@Table(name="transportagent"
    ,catalog="travelandtourism"
)
public class Transportagent  implements java.io.Serializable {


     private Integer tagentid;
     private String tagentname;
     private String tagentmobile;
     private String tagentaddress;
     private String email;

    public Transportagent() {
    }

    public Transportagent(String tagentname, String tagentmobile, String tagentaddress, String email) {
       this.tagentname = tagentname;
       this.tagentmobile = tagentmobile;
       this.tagentaddress = tagentaddress;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tagentid", unique=true, nullable=false)
    public Integer getTagentid() {
        return this.tagentid;
    }
    
    public void setTagentid(Integer tagentid) {
        this.tagentid = tagentid;
    }

    
    @Column(name="tagentname", nullable=false, length=45)
    public String getTagentname() {
        return this.tagentname;
    }
    
    public void setTagentname(String tagentname) {
        this.tagentname = tagentname;
    }

    
    @Column(name="tagentmobile", nullable=false, length=45)
    public String getTagentmobile() {
        return this.tagentmobile;
    }
    
    public void setTagentmobile(String tagentmobile) {
        this.tagentmobile = tagentmobile;
    }

    
    @Column(name="tagentaddress", nullable=false, length=450)
    public String getTagentaddress() {
        return this.tagentaddress;
    }
    
    public void setTagentaddress(String tagentaddress) {
        this.tagentaddress = tagentaddress;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


