package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Transportdetails generated by hbm2java
 */
@Entity
@Table(name="transportdetails"
    ,catalog="travelandtourism"
)
public class Transportdetails  implements java.io.Serializable {


     private Integer transdetid;
     private int tagentid;
     private int tpackid;
     private String transtype;
     private String transdetails;
     private String image;

    public Transportdetails() {
    }

    public Transportdetails(int tagentid, int tpackid, String transtype, String transdetails, String image) {
       this.tagentid = tagentid;
       this.tpackid = tpackid;
       this.transtype = transtype;
       this.transdetails = transdetails;
       this.image = image;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="transdetid", unique=true, nullable=false)
    public Integer getTransdetid() {
        return this.transdetid;
    }
    
    public void setTransdetid(Integer transdetid) {
        this.transdetid = transdetid;
    }

    
    @Column(name="tagentid", nullable=false)
    public int getTagentid() {
        return this.tagentid;
    }
    
    public void setTagentid(int tagentid) {
        this.tagentid = tagentid;
    }

    
    @Column(name="tpackid", nullable=false)
    public int getTpackid() {
        return this.tpackid;
    }
    
    public void setTpackid(int tpackid) {
        this.tpackid = tpackid;
    }

    
    @Column(name="transtype", nullable=false, length=45)
    public String getTranstype() {
        return this.transtype;
    }
    
    public void setTranstype(String transtype) {
        this.transtype = transtype;
    }

    
    @Column(name="transdetails", nullable=false, length=450)
    public String getTransdetails() {
        return this.transdetails;
    }
    
    public void setTransdetails(String transdetails) {
        this.transdetails = transdetails;
    }

    
    @Column(name="image", nullable=false, length=4500)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


