package com.project.traveltourism.model;
// Generated Oct 29, 2020 2:28:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="travelandtourism"
)
public class User  implements java.io.Serializable {


     private String emailid;
     private String phoneno;
     private String username;

    public User() {
    }

    public User(String emailid, String phoneno, String username) {
       this.emailid = emailid;
       this.phoneno = phoneno;
       this.username = username;
    }
   
     @Id 

    
    @Column(name="emailid", unique=true, nullable=false, length=45)
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    
    @Column(name="phoneno", nullable=false, length=45)
    public String getPhoneno() {
        return this.phoneno;
    }
    
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    
    @Column(name="username", nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


